name: Create Markdown

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/service/*.json'

jobs:
  webpage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install groovy
        run: sudo apt install groovy

      - name: Generate website
        run: cd docs/service ; groovy createMarkdown.groovy *.json

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add docs/service/*.md
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Updated service Markdown '
              git push
          fi
