## Get all .rst files in list
## Convert them to .md
## Copy all these .md files to ./docs 

library(tidyverse)

pandoc_converter <- function(path_in, path_out) {
  # Check if pandoc is installed
  if (system("which pandoc", intern = TRUE) == "") {
    stop("pandoc is not installed. Please install pandoc to use this function.")
  }
  
  # Construct the pandoc command
  cmd <- sprintf("pandoc %s -o %s", path_in, path_out)
  
  # Execute the command
  system(cmd)
  
  # Inform the user
  cat(sprintf("File converted and saved to: %s\n", path_out))
}

# Example usage:
# convert_rst_to_md("input_file.rst", "output_file.md")

intro_files <- list.files(
  path = "./read-the-docs-sphinx",
  pattern = "intro.rst",
  full.names = TRUE,
  recursive = TRUE
)

## remove autogenerated .rst files 'intro.rst'
#map(
#  .x = intro_files,
#  .f = file.remove
#)

# .rst files that are left
rst_files <- list.files(
  path = "./read-the-docs-sphinx",
  pattern = ".rst",
  full.names = TRUE,
  recursive = TRUE
)

ipynb_files <- list.files(
  path = "./read-the-docs-sphinx",
  pattern = ".ipynb",
  full.names = TRUE,
  recursive = TRUE
)

## dummies
# path <- rst_files[[1]]
# extension <- ".md"
# path_out <- "./docs"

dir.create(here::here("docs", "tutorials"))
dir.create(here::here("docs", "resources"))
dir.create(here::here("docs", "topics"))
dir.create(here::here("docs", "services"))

create_new_name <- function(path_in, path_out, extension = ".md"){
  
  new_name <- path_in |>
    basename() |>
    tools::file_path_sans_ext()
  
  new_name <- paste0(new_name, extension)
  new_path <- file.path(path_out, new_name)
  return(new_path)
}

## get all new paths
new_paths <- map_chr(
  .x = rst_files,
  .f = create_new_name,
  path_out = "./docs/services",
  extension = ".md"
)

## convert .rst to .md
walk2(
  .x = rst_files,
  .y = new_paths,
  .f = pandoc_converter
)

## convert ipynb to md
walk2(
  .x = rst_files,
  .y = new_paths,
  .f = pandoc_converter
)

## copy files
names(new_paths) <- basename(rst_files)
file.rename(
  from = new_paths["Tutorials.rst"],
  to = file.path("docs", "tutorials", "tutorials.md"))
file.rename(
  from = new_paths["Topics.rst"],
  to = file.path("docs", "topics", "topics.md"))
file.rename(
  from = new_paths["RESOURCES.rst"],
  to = file.path("docs", "resources", "resources.md"))
file.rename(
  from = new_paths["gene_identifier_mapping.rst"],
  to = file.path("docs", "tutorials", "gene_identifier_mapping.md"))
file.rename(
  from = new_paths["site_of_metabolism_prediction.rst"],
  to = file.path("docs", "tutorials", "site_of_metabolism_prediction.md"))

## copy index to project root
file.rename(
  from = new_paths["index.rst"],
  to = file.path("docs", "index.md")
)

